import os

PREFIX = "DOTTOOLS"

HOST_NAME_ENV = f"{PREFIX}_HOST_NAME"
CONFIG_FILE_PATH_ENV_VAR = f"{PREFIX}_CFG_PATH"

ROOT_PATH_ENV_VAR = f"{PREFIX}_ROOT_PATH"
BASHRCD_PATH_ENV = f"{PREFIX}_BASHRCD_PATH"
BIN_PATH_ENV = f"{PREFIX}_BIN_PATH"
LIB_PATH_ENV = f"{PREFIX}_LIB_PATH"
SCRIPTS_PATH_ENV = f"{PREFIX}_SCRIPTS_PATH"
DOCKER_PATH_ENV = f"{PREFIX}_DOCKER_PATH"
DOCKER_BIN_PATH_ENV = f"{PREFIX}_DOCKER_BIN_PATH"
PROMPT_ENV_VAR = f"{PREFIX}_PROMPT"
