#!/usr/bin/env python3

import os
import argparse

import dd_context
import dd_bashrc
import dd_dots
import util.dd_env


def parse_args():
    parser = argparse.ArgumentParser(description='The .bashrc and dottools installer tool')

    parser.add_argument(
        '--config-file', '-c',
        help='Configuration description (.yaml)',
        default=os.getenv(util.dd_env.CONFIG_FILE_PATH_ENV_VAR),
    )
    parser.add_argument(
        '--root',
        help='dottols root directory',
        default=os.getenv(
            util.dd_env.ROOT_PATH_ENV_VAR,
            default=os.path.dirname(os.path.dirname(__file__)),
        ),
    )
    parser.add_argument(
        '--dry-run',
        help='Only print which actions will be done instead of doint anything',
        default=False,
        action='store_true',
    )
    parser.add_argument(
        '--log-level', '-l',
        help='Logging level [0..3]',
        default=1,
        action='store',
        type=int,
    )

    subparsers = parser.add_subparsers(title='Commands', dest='command')

    bashrc_parser = subparsers.add_parser('bashrc', help='Install .bashrc')
    dots_parser = subparsers.add_parser('dotfiles', help='Install dotfiles')
    all_parser = subparsers.add_parser('all', help='Apply everything')
    diff_parser = subparsers.add_parser('diff', help='Equivalent to "dots --dry-run all"')

    return parser.parse_args()


def main(args):
    if args.command == 'diff':
        args.dry_run = True

    context = dd_context.Context(
        config_path=os.path.realpath(args.config_file),
        dot_root=os.path.realpath(args.root),
        dry_run=args.dry_run,
        log_level=args.log_level,
    )

    if args.command in {'bashrc', 'all'}:
        with context.logger.indent(offset=0, label='bashrc'):
            dd_bashrc.process(context, context.cfg['bashrc'])

    if args.command in {'dotfiles', 'all'}:
        with context.logger.indent(offset=0, label='dots'):
            dd_dots.process(context, context.cfg.get('dots', []))

    if args.command in {'diff'}:
        with context.logger.indent(offset=0, label='bashrc'):
            dd_bashrc.process(context, context.cfg['bashrc'])
        with context.logger.indent(offset=0, label='dots'):
            dd_dots.process(context, context.cfg.get('dots', []))


if __name__ == '__main__':
    main(parse_args())
