name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CI and Tests' dependencies
      run: |
        python -m pip install black==24.2.0 pytest==8.0.0

    - name: Run black formatting check
      run: python -m black --check --diff dots .

    - name: Run tests
      run: python -m pytest
